export function montarDadosCliente(data: any) {
  return {
    nome: data.nome,
    razaoSocial: data.razaoSocial || null,
    nomeFantasia: data.nomeFantasia || null,
    cnpjCpf: data.cnpjCpf || null,
    tipoPessoa: data.tipoPessoa || 'juridica',
    regimeTributario: data.regimeTributario,
    inscricaoEstadual: data.inscricaoEstadual || null,
    inscricaoMunicipal: data.inscricaoMunicipal || null,
    email: data.email || null,
    telefone: data.telefone || null,
    responsavel: data.responsavel || null,
    cep: data.cep || null,
    logradouro: data.logradouro || null,
    numero: data.numero || null,
    complemento: data.complemento || null,
    bairro: data.bairro || null,
    cidade: data.cidade || null,
    estado: data.estado || null,
    situacaoCadastral: data.situacaoCadastral || null,
    atividadePrincipal: data.atividadePrincipal || null,
    dataAbertura: data.dataAbertura ? new Date(data.dataAbertura) : null,
    clienteDesde: data.clienteDesde ? new Date(data.clienteDesde) : null,
    possuiFuncionarios: data.possuiFuncionarios ?? false,
    possuiIcms: data.possuiIcms ?? false,
    possuiRetencoes: data.possuiRetencoes ?? false,
    observacoes: data.observacoes || null,
    ativo: data.ativo ?? true,
  }
}
